name: Build and upload to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-24.04
    permissions:
      id-token: write  # mandatory for PyPI trusted publishing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
          architecture: x64

      - name: Build packages
        run: |
          pip install -U pip build
          python -m build --sdist --wheel

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.8
        # dont specify anything for Trusted Publishing
        # https://docs.pypi.org/trusted-publishers
        # with:
        #  # Using token
        #  user: __token__
        #  password: ${{ secrets.PYPI_API_TOKEN }}
        #
        #  # Using token on test index
        #  password: ${{ secrets.PYPI_TEST_API_TOKEN }}
        #  repository_url: https://test.pypi.org/legacy/

      - name: Build and push Docker image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: openzim/great-project
          tag-pattern: /^v([0-9.]+)$/
          latest-on-tag: true
          restrict-to: openzim/_python-bootstrap
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
          repo_description: auto
          repo_overview: auto
